spring.application.name=CustomerService
server.port=8081

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://customer-mysql:3306/Customer-service}
spring.datasource.username=${CUSTOMER_DB_USER}
spring.datasource.password=${CUSTOMER_DB_PASS}

spring.jpa.hibernate.ddl-auto=update
