apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-secrets
type: Opaque
stringData:
  JWT_SECRET: "bu5HenKK9pCurkUUic604aWzpvY4XruaVZsIkArn0EE9M9GFfTX1vq3vSubM1gwyrZB0Fs22yv5XsWt8jxbT8h"

  BOOKING_DB_NAME: "Booking-service"
  BOOKING_DB_URL: "jdbc:mysql://booking-db:3306/Booking-service"
  BOOKING_DB_USERNAME: "booking_user"
  BOOKING_DB_PASSWORD: "booking_password"
  BOOKING_DB_ROOT_PASSWORD: "root_booking_password"

  CUSTOMER_DB_NAME: "Customer-service"
  CUSTOMER_DB_URL: "jdbc:mysql://customer-db:3306/Customer-service"
  CUSTOMER_DB_USERNAME: "customer_user"
  CUSTOMER_DB_PASSWORD: "customer_password"
  CUSTOMER_DB_ROOT_PASSWORD: "root_customer_password"

  REVIEW_DB_NAME: "Review-service"
  REVIEW_DB_URL: "jdbc:mysql://review-db:3306/Review-service"
  REVIEW_DB_USERNAME: "review_user"
  REVIEW_DB_PASSWORD: "review_password"
  REVIEW_DB_ROOT_PASSWORD: "root_review_password"